### ISSUE TITLE
Return Cadastre Geometry for Exact Street Match

### ISSUE THREAD

**Issue by 3DXScape** [polysteve/MobileLocater#8]

**Comment by polysteve** [comment]
#### Reproduce: Enter 2030 Whitney Ave, Hamden, CT

#### Result: Geometry follows old CBYD requirement for full block - not just address in request

#### Expected: Geometry localized to named address

**Comment by 3DXScape** [comment]
This is now mostly working. Where an address is available for a parcel,  the parcel geometry is returned. Where not available, the location is on the street centreline and no longer extended to the length of a block with the representative point in the center of the block as was the previous rule at CBYD.

**Comment by 3DXScape** [comment]
Closed
